title: Srikanth Venugopalan
description: "writes code, loves hacking.<br />From Chennai, India"

url: http://sriv.github.io
permalink: pretty

twitter: stylish_steam
github: sriv

server: true
auto: true